# Page settings

baseURL = "https://resume-chvmuralikumar/"
languageCode = "en"
title = "CH V Muralikumar"
enableGitInfo = false
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "CH V Murali Kumar"
    description = "Muralikumar Resume"
    og_image = "better-software.png"
    twitterName = "@bascodes"
    ghRepo = "https://github.com/muralikumarch/resume_1/"
    hugoRepo = "https://github.com/gohugoio/hugo/"

    [params.profile]
        enable = true
        name = "CH V Muralikumar"
        tagline = "Principal Java Developer"
        avatar = "MyPhoto.jpg"

    [params.contact]
        enable = true

        location = "Hyderabad, IN"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:"
        text = "+91-9989225431"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:muralikumar.ch@gmail.com"
        text = "muralikumar.ch@gmail.com"
        [[params.contact.list]]
        icon = "fa-brands fa-linkedin-in"
        url = "https://www.linkedin.com/in/chvmuralikumar/"
        text = "LinkedIn @chvmuralikumar"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical" 
        [[params.skills.list.items]]
        title = "Java, Spring, Springboot, Hibernate"
        [[params.skills.list]]
        title = "Azure"
        [[params.skills.list]]
        title = "Professional" 
        details = "Effective communication, Team player"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Master of Computer Applications"
        university = "Andhra University, Vishakapatnam"
        dates = "2003-2006"

        [[params.education.list]]
        degree = "Bachelor of Science (B.Sc. CS)"
        university = "Andhra University, Vishakapatnam"
        dates = "2000-2003"


    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Java SE 8 Programmer - OCP"
        body = "Oracle"
        date = "2019"
        
        [[params.awards.list]]
        name = "Java Spring Framework"
        body = "Coursera"
        date = "2021"

        [[params.awards.list]]
        name = "Azure Developer Associate"
        body = "Microsoft"
        date = "2022"

        [[params.awards.list]]
        name = "Azure Solutions Architect Expert"
        body = "Microsoft"
        date = "2022"

        [[params.awards.list]]
        name = "Power Platform App Maker Associate"
        body = "Microsoft"
        date = "2022"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Telugu"
        level = "Fluent"

        [[params.languages.list]]
        name = "English"
        level = "Fluent"


    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Counting Sheeps"


    [params.summary]
        enable = true
        text = "Highly motivated and experienced software professional with over 15+ years of experience in Java and Microsoft Azure. Adept at using Java/J2EE, Spring Framework, Hibernate, and various Azure services to develop and deploy secure, scalable, and high performing applications. Excellent problem-solving and communication skills with a strong ability to work in a team environment"


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "PRINCIPAL JAVA DEVELOPER"
        dates = "Sep 2014 - Present"
        company = "Parexel International (India) Pvt Ltd – Hyderabad"
        details = "Increased the baudrate for comic book guy"
        [[params.experience.list.items]]
        details = "Use Java/J2EE, Spring, Spring boot, Hibernate technologies to develop web applications for client server environments and add functionalities to existing applications."
        details = "Conduct user requirements analysis to design and program applications and deliver support for system enhancement."
        details = "Play a pivotal role as a part of an agile scrum team accountable, developing new applications using Spring framework."
        details = "Involved in development of various stories and bugs of various for VCAS (Virtual Clinical Adjudication System) projects and contribute to other technical documentation activities. Developed UI and Service layer components for various modules."
        details = "Hands on experience in Azure Development, worked on Azure web application, App services, Azure storage, Azure SQL Database, Virtual machines."
        details = "Designed, configured, and deployed Microsoft Azure for a multitude of applications utilizing the Azure, focusing on high - availability, fault tolerance, and auto-scaling."
        details = "Developed methodologies for cloud migration, implemented best practices and helped to develop backup and recovery techniques for applications and database on virtualization platform."

        [[params.experience.list]]
        title = "SENIOR SOFTWARE ENGINEER"
        dates = "Oct 2013 – Sep 2014"
        company = "Kony IT Services Pvt Ltd. – Hyderabad"
        details = "Increased the baudrate for comic book guy"
        [[params.experience.list.items]]
        details = "Involved various mobile apps development with Kony Mobile Platform.
                   Involved in implementing custom features, UI design along with business team
                   Developed and integrated processes into system life cycle management"

        



    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "This Resume"
        meta = "GitHub project"
        url = "https://github.com/codewithbas/resume"
        tagline = "A resume with a free PDF generator"


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Cooking, Beekeeping, Cycling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/codewithbas"
        title = "/codewithbas"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/bascodes"
        title = "/in/bascodes"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "https://twitter.com/bascodes"
        title = "@bascodes"
